### ISSUE TITLE
Feature Request: support for extracting documentation from templates

### ISSUE THREAD

**Issue by drybjed** [htgoebel/yaml2rst#1]
Ansible roles have templates in random places which are written in Jinja2. Jinja2 provides a way to add comments to the templates which are not rendered, for example:

```
{# This won't be rendered #}
```

I would like to document these templates using reStructuredText inside these comment sections, but to not have random sections extracted, that would require a top and bottom marker to tell `yaml2rst` which section of the file to extract and convert, for example:

```
{#
# =====yaml2rst-top=====
# .. _postfix_template_main_cf:
# Postfix template: /etc/postfix/main.cf
# ======================================
# =====yaml2rst-bottom=====
#}
```

With this formatting, `yaml2rst` could grab the specified file, cut the not selected parts from top and bottom, and convert the rest to RST. Having these markers configurable would be a bonus.

[Edit by htgoebel: Split into two issues, see #2]

**Comment by htgoebel** [comment]
IMHO this should go into a separate tool `jinja2rst`. I'll put that on my todo list.

**Comment by htgoebel** [comment]
[jinja2rst](https://github.com/htgoebel/jinja2rst) is written and now available in PyPI.
