### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by KingJ** [htgoebel/yaml2rst#9]
Hi,

Would it be possible to create a new release of yaml2rst? There are some useful things in the develop branch that would be great to use from a numbered version rather than pulling the develop branch directly.

Many thanks!

**Comment by KingJ** [comment]
Sorry to bother you @htgoebel , but I can see some updates were made to the develop branch shortly after I logged this issue. Is a release likely to follow soon?

Many thanks.

**Comment by htgoebel** [comment]
This as bben th plan, but I was distracted by some issues with zest.releaser or more precisely twine not providing a simple way to "call" it.

**Comment by htgoebel** [comment]
Done, see cc4d831f76b7cbbe58652f0f594e725e901f44e2.

Release 0.3 is available at PyPi https://pypi.org/project/yaml2rst/
